./run.sh 0 python3 src/main.py --config=ppo_rnn --env-config=stag_hunt with name="ppo" label="ppo_stag_hunt_test_mingefei" &
./run.sh 1 python3 src/main.py --config=ppo_rnn --env-config=stag_hunt with name="ppo" label="ppo_stag_hunt_test_mingefei" &
./run.sh 2 python3 src/main.py --config=ppo_rnn --env-config=stag_hunt with name="ppo" label="ppo_stag_hunt_test_mingefei" &
./run.sh 3 python3 src/main.py --config=iql --env-config=stag_hunt with name="iql" label="ppo_stag_hunt_test_mingefei" &
./run.sh 4 python3 src/main.py --config=iql --env-config=stag_hunt with name="iql" label="ppo_stag_hunt_test_mingefei" &
./run.sh 5 python3 src/main.py --config=iql --env-config=stag_hunt with name="iql" label="ppo_stag_hunt_test_mingefei" &
./run.sh 3 python3 src/main.py --config=qmix --env-config=stag_hunt with name="qmix" label="ppo_stag_hunt_test_mingefei" &
./run.sh 4 python3 src/main.py --config=qmix --env-config=stag_hunt with name="qmix" label="ppo_stag_hunt_test_mingefei" &
./run.sh 5 python3 src/main.py --config=qmix --env-config=stag_hunt with name="qmix" label="ppo_stag_hunt_test_mingefei" &
